spring:  application:    name: fdxConfigServerserver:  port: 8888 eureka:  client:    register-with-eureka: true    fetch-registry: true    service-url:       defaultZone: https://eurekaserverfdx.cfapps.io/eureka#      defaultZone: http://localhost:8761/eureka  

